steps:
  # go build
  - name: 'golang:1.20-buster'
    entrypoint: '/bin/bash'
    dir: 'src/'
    args:
      - -c
      - |
        go mod download
        go mod tidy
        CGO_ENABLED=0 GOOS=linux go build -o main ./main.go
  # docker build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
          '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/tools/status-check-notify-slack:$TAG_NAME',
          '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/tools/status-check-notify-slack:latest',
          '--cache-from', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/tools/status-check-notify-slack:latest',
          '-f', 'Dockerfile.slim',
          '.'
    ]
  # docker push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '-a', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/tools/status-check-notify-slack']

images:
  - asia-northeast1-docker.pkg.dev/$PROJECT_ID/tools/status-check-notify-slack